### ISSUE TITLE
global overrides

### ISSUE THREAD

**Issue by arve0** [zoltantothcom/vanilla-js-carousel#1]
Hi, nice lib!
I find [the global overrides](https://github.com/zoltantothcom/vanilla-js-carousel/blob/gh-pages/styles/vanilla-js-carousel.scss#L115-L186) a bit intrusive. Any reason why they are in the "production build"?

**Comment by zoltantothcom** [comment]
Perfectly valid point - decoration page styles and scripts belong to gh-pages branch. I removed everything irrelevant from the so-called "production build". Thank you!
