### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by freepad** [zoltantothcom/vanilla-js-carousel#2]
Hello!

Can you add lib on npm?

**Comment by zoltantothcom** [comment]
Sure! Should be ready soon.

**Comment by zoltantothcom** [comment]
> Hello!
> Can you add lib on npm?

Please find it here - 
[https://www.npmjs.com/package/vanilla-js-carousel](https://www.npmjs.com/package/vanilla-js-carousel "Vanilla JS Carousel")
