### ISSUE TITLE
live() method value does not reset in infinite mode 

### ISSUE THREAD

**Issue by gterras** [zoltantothcom/vanilla-js-carousel#7]
Hi ! 

Thanks for your very nice plugin. I've been through a lot of plugins like these before finally finding yours, which is very light and gives all the options I need. 

I have noticed the `live()` method does not return the correct value in infinite mode after the first loop. 

Say you have 4 slides looping indefinitely, the `live()` method should return (in my opinion) : 

 `0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3...` 

But instead it returns : 

`0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10...`

Is this a wanted behavior ? 

Thanks for your help!

**Comment by zoltantothcom** [comment]
Hi!

Thanks for your finding - this is definitely not the wanted behavior.  
Your assumption of the order (`0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3...`) is correct.

**Comment by zoltantothcom** [comment]
@gterras I've created a quick [JSBin](http://jsbin.com/yowehoxidu/edit?html,js,console) and it seems to output the correct values. Can you please share a bit more about your use case when does the error happen? Thanks!

**Comment by gterras** [comment]
Hi @zoltantothcom, 

Thank you for your answer. I have boiled down the case to the option `dots : false`, just change this in your demo and the bug will show up. 

I suppose this code is responsible  : 

    function adjustCurrent(val) {
        current += val;
  
        if (options.dots) { // If dots:false, current is perpetually incremented 
            currentDot();
        }
    }

Thank you and have a nice day !

**Comment by zoltantothcom** [comment]
Thank you for taking the time to report the issue! Now it's fixed.

**Comment by gterras** [comment]
Nice work, thank you !
