### ISSUE TITLE
Not working for multiple carousels on the same page

### ISSUE THREAD

**Issue by yaroslavputria** [zoltantothcom/vanilla-js-carousel#8]
Please replace document.querySelectorAll with element.querySelectorAll (where element is current carousel 'div') in 'showPrevInfinite', 'showPrevLinear', 'showNextInfinite' and 'showNextLinear' functions.

**Comment by zoltantothcom** [comment]
Thank you for raising the issue. I'll look into that shortly.

**Comment by rdourado** [comment]
+1

**Comment by zoltantothcom** [comment]
Fixed.
